[package]
name = "common"
version = "0.1.0"
authors = ["Nathan Ringo <remexre@gmail.com>"]

[dependencies]
failure = "0.1.2"
glium = "0.18.0"
glium_sdl2 = "0.15.0"
image = "0.19.0"
log = "0.4.5"
sdl2 = "0.30.0"
stderrlog = "0.4.1"
structopt = "0.2.10"
